TWEAK_NAME = Eneko
Eneko_FILES = Eneko.x
Eneko_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
Eneko_FRAMEWORKS = AVFoundation UIKit
Eneko_EXTRA_FRAMEWORKS = Cephei
Eneko_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
