export ARCHS = arm64 arm64e
INSTALL_TARGET_PROCESSES = SpringBoard

SUBPROJECTS += NetflixToggle 

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
